#ifndef NUEVA_RESERVA_SONIADA_ADOPTAR_ANIMAL_CONTROLLERS_H
#define NUEVA_RESERVA_SONIADA_ADOPTAR_ANIMAL_CONTROLLERS_H
#include "ArbolB.h"

void adoptar_animal(ArbolB<Animal*> &registro_de_animales);

#endif //NUEVA_RESERVA_SONIADA_ADOPTAR_ANIMAL_CONTROLLERS_H
